### PR TITLE
Avoid trailing null on hex encoded TCP

### LINKED ISSUE #175: TCP transport nulls all payload bytes
As of 0.9.8, it looks like using TCP transport between two processes nulls all the request bytes.

I was able to reproduce this with `--input-file=before.bin --output-tcp localhost:9000` and `--input-tcp :9000 --output-file=after.bin`.

It looks like this was introduced in 4d00ff87, specifically the `\n` byte appended to the hex encoded payload in output_tcp.go is causing the hex.Decode in input_tcp.go to fail (silently), leaving `decoded` empty.

### PR DESCRIPTION
**Pull request by dt**
Also fail loudly if hex decoding fails, as otherwise a request of just null bytes is handed to output.

Fixes #175.

### CODE REVIEW

File: input_tcp.go [hunk 1]
```diff
@@ -66,8 +66,12 @@ func (i *TCPInput) handleConnection(conn net.Conn) {
 	for scanner.Scan() {
 		encodedPayload := scanner.Bytes()
 		// Hex encoding always 2x number of bytes
-		decoded := make([]byte, len(encodedPayload)/2)
-		hex.Decode(decoded, encodedPayload)
+		size := len(encodedPayload)
+		decoded := make([]byte, size/2)
+		_, err := hex.Decode(decoded, encodedPayload[:size-1])
+		if err != nil {
+			log.Fatal("[TCPInput] failed to hex decode TCP payload:", err)
```
Comment (buger) [inline input_tcp.go]: I'm not sure about `Fatal` since it will stop Gor. Maybe make sense just to print.

**Comment by buger** [comment]
Weird, frankly i can't really replicate it. Scanner by default strips trailing "\n" at the end...

**Comment by dt** [comment]
Oh, you're right, the scanner is timing the \n -- it's actually a trailing null byte that is causing hex decode to fail. It looks like that is because, in output_tcp.go, the allocation of `encoded` makes it `len(data)*2+1`, but then the `append` call extends it to add the `\n`... so there's the data*2 hex bytes, a null and then the newline. Looks like removing the `+1` should fix it.

**Comment by buger** [comment]
To avoid memory allocation its better to keep +1, and instead do:
```go
encoded := make([]byte, len(data)*2+1)
encoded[len(encoded)-1] = '\n'
hex.Encode(encoded, data)
o.buf <- encoded
```

`append` internally checks length of the array, and do additional memory allocation.

**Comment by buger** [comment]
:+1:

**Comment by buger** [comment]
Included into [v0.9.8](https://github.com/buger/gor/releases/tag/0.9.8)
